name: Bug Report
description: File a bug report.
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what has happened.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect?
      description: Tell us what you expected to happen?
      placeholder: Tell us what you expect!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce this error?
      description: Tell us how we can reproduce this error.
      placeholder: Tell us the steps to reproduce this error!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
